module.exports = [
  "What is your favorite candy?",
  "If you had to change the name of your father - what would you change it to?",
  "What is your spirit animal?",
  "Top 3 movies?",
  "Who is your favorite streamer to watch?",
  "What surprised you about streaming?",
  "What is your guilty pleasure?",
  "Is mayonnaise good?",
  "Do you like pineapple on pizza?",
  "What would you do with 1 million dollars?",
  "Do you have any tattoos? If not, will you ever?",
  "Is water wet?",
  "Who is your least favorite popular streamer?",
  "Do you think Twitch will be around in 15 years?",
  "Family is coming over - what are you doing for dinner?",
  "Do you consider yourself to be more extroverted or introverted?",
  "What sports did you play as a kid?",
  "What was the last book you read?",
  "Who was your least favorite teacher in school?",
  "Do you find streaming to be relaxing?",
  "What is the best video game ever made?",
  "Can you speak any other languages?",
  "Why is the Lord of the Rings Trilogy the best movies ever made?",
  "Have you ever met a Karen in real life?",
  "Have you ever purchased dogecoin?",
  "What is the most embarassing thing to ever happen to you?",
  "Have you ever slept under the stars?",
  "When was the last time you barfed?",
  "What is your happiest memory from streaming?",
  "Who would win in a fight - a taco or a hot dog?",
  "Do you believe in love at first sight?",
  "Would you ever get a face tattoo?",
  "What is your biggest pet peeve?",
  "Have you ever fallen asleep in a classroom?",
  "Do you agree that you should never talk about politics at the dinner table?",
  "What is something that is on your bucket list?",
  "Would you go skydiving tomorrow if you had a free ticket?",
  "What is the scariest thing you have done?",
  "Do you think people will go to mars in your lifetime?",
  "Do aliens exist?",
  "Do you believe in any conspiracy theories?",
  "What is the first video game you ever played?",
  "Do you want to become a full-time streamer?",
  "Would you consider yourself to be spiritual?",
  "What is the easiest money you have ever made?",
  "Would you jump into a pool of jello?",
  "What is one of the worst movies you have ever watched?",
  "Should everone go to college?",
  "Have you ever been bitten by an animal?",
  "You are given $100. How do you use it for your stream?",
  "Have you ever cracked open a pinata?",
  "Who is your second favorite family member?",
  "Have you ever been in a band?",
  "What did you eat for breakfast today?",
  "Are Zoos ethical?",
  "What is the ugliest animal in the world?",
  "Would you ever shave ALL of the hair on your body?",
  "What is a podcast that you enjoy listening to?",
  "Do you like Taylor Swift music?",
  "What is an underrated video game?",
  "Can you play an instrument?",
  "Would you eat the hottest pepper in the world for $1000 dollars?",
  "What is the longest you have gone without bathing?",
  "Do you enjoy shopping?",
  "How do your friends describe you?",
  "What is the longest you have stayed awake?",
  "Would you ever do a 24 hour stream?",
  "What is the best advice you would give to a new streamer?",
  "You find yourself in the Star Wars universe - which side are you on?",
  "Who is the greatest musician that ever lived?",
  "Thoughts on black licorice?",
  "Would you sell one of your toes for $300k?",
  "Do you enjoy Mondays?",
  "What was the best job you ever had?",
  "Does bigfoot exist?",
  "Have you ever met a famous person?",
  "Would you want to go to TwitchCon?",
  "Favorite place you have traveled to?",
  "What is the perfect ice cream?",
  "If could only drink one thing (besides water) for the rest of your life - what would you choose?",
  "Have you ever hitchhiked before?",
  "Have you ever gotten poison oak?",
  "What is your favorite sports team?",
  "Have you ever dreamed on dinosaurs?",
  "Is Jeff Bezos a good guy?",
  "What is the most people you ever had on your stream?",
  "How old will you live to?",
  "Would you ride on a hippo if you had the chance?",
  "Can you hold your breath more than 60 seconds?",
  "What is the most money you have found on the ground?",
  "Do you enjoy getting a haircut?",
  "What is your dream job?",
  "Are video games art?",
  "Have you ever been told you look like someone famous, who was it?",
  "Does your current car have a name? What is it?",
  "If you were famous, what would you be famous for?",
  "If you could add anyone to Mount Rushmore who would it be?",
  "If you could magically have anything come out of your belly button - what would it be?",
  "Are you sunrise, daylight, twilight, or nighttime? Why?",
  "Would you rather have invisibility or flight?",
  "What school subject is your favorite?",
  "If you could have any animal for a pet, what would it be?",
  "If you could switch lives with anyone for a day, who would it be?",
  "The zombie apocalypse is coming, what do you do?",
  "What is your most used emoji?",
  "What was the worst haircut you ever had?",
  "How would you describe your stream viewers?",
  "Who was your childhood actor/actress crush?",
  "If you were a wrestler what would be your theme song?",
  "Public speaking - love it or hate it?",
  "You have to sing karaoke, what song do you pick?",
  "What was your least favorite food as a child?",
  "Describe the perfect tuna sandwich",
  "if you had to stream only one video game - what would it be?",
  "If you had a job at Disneyland - what would it be?",
  "What is your favorite magical or mythological animal?",
  "You arere going sail around the world, what’s the name of your boat?",
  "Is Justin Bieber talented?",
  "You can have lunch with two other streamers - who would you choose?",
  "What breed of dog would you be?",
  "Are you a traveler or a homebody?",
  "What languages do you know how to speak?",
  "Are you a good dancer?",
  "Do you enjoy weddings?",
  "If you could see one movie again for the first time, what would it be and why?",
  "If you could instantly become an expert in something, what would it be?",
  "If you could have the power of teleportation right now, where would you go and why?",
  "Would you rather be able to run at 100 miles per hour or fly at 10 miles per hour?",
  "Would you rather be the funniest or smartest person in the room?",
  "Would you rather be a turtle or a turkey?",
  "Would you rather always be slightly late or super early?",
  "If your pet could talk, what do you think it would say?",
  "Which cartoon character do you wish was real?",
  "Favorite smell?",
  "If you were invisible for a day, what would you do?",
  "How many channels do you subcribe to (YouTube or Twitch)?"
]